config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    get '/dev' => 'welcome#index_dev'
  end
  get 'welcome/index'
  root 'welcome#index'

  get '/features' => 'welcome#features'
  resources :folders
  get 'folders/from_folder/:id' => 'folders#from_folder'
  delete 'folders/delete/:folder_id/:name' => 'folders#delete'
  get 'folders/delete/:folder_id/:name' => 'folders#get_delete'
  resources :file_items
  get 'file_items/from_folder/:id' => 'file_items#from_folder'

end

app/models/file_item.rb
class FileItem < ActiveRecord::Base
  belongs_to :folder
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  has_many :folder
  has_many :file_items
  belongs_to :folder
  validates_uniqueness_of :name, scope: :folder_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/file_items_controller.rb
class FileItemsController < ApplicationController
  before_action :set_file_item, only: [:show, :edit, :update, :destroy]

  # GET /file_items
  # GET /file_items.json
  def index
    @file_items = FileItem.all
  end

  def from_folder
    @file_items = FileItem.where(folder_id: params[:id])
  end

  # GET /file_items/1
  # GET /file_items/1.json
  def show
  end

  # GET /file_items/new
  def new
    @file_item = FileItem.new
  end

  # GET /file_items/1/edit
  def edit
  end

  # POST /file_items
  # POST /file_items.json
  def create
    @file_item = FileItem.new(file_item_params)

    respond_to do |format|
      if @file_item.save
        format.html { redirect_to @file_item, notice: 'File item was successfully created.' }
        format.json { render :show, status: :created, location: @file_item }
      else
        format.html { render :new }
        format.json { render json: @file_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /file_items/1
  # PATCH/PUT /file_items/1.json
  def update
    respond_to do |format|
      if @file_item.update(file_item_params)
        format.html { redirect_to @file_item, notice: 'File item was successfully updated.' }
        format.json { render :show, status: :ok, location: @file_item }
      else
        format.html { render :edit }
        format.json { render json: @file_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /file_items/1
  # DELETE /file_items/1.json
  def destroy
    @file_item.destroy
    respond_to do |format|
      format.html { redirect_to file_items_url, notice: 'File item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_file_item
      @file_item = FileItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def file_item_params
      params.require(:file_item).permit(:name, :folder_id)
    end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:show, :edit, :update, :destroy]
  before_action :set_folder_with_name, only: [:delete, :get_delete]


  # GET /folders
  # GET /folders.json
  def index
    @folders = Folder.all
  end

  def from_folder
    @root = params[:id]=='-1' ? Folder.new(name: 'root', id: -1) : Folder.find(params[:id])
    @folders = Folder.where(folder_id: params[:id]=='-1' ? nil : params[:id])
  end

  def delete
    @folder.destroy_all
    respond_to do |format|
      format.html { redirect_to folders_url, notice: 'Folder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_delete
    render json: @folder
  end

  # GET /folders/1
  # GET /folders/1.json
  def show
  end

  # GET /folders/new
  def new
    @folder = Folder.new
  end

  # GET /folders/1/edit
  def edit
  end

  # POST /folders
  # POST /folders.json
  def create
    @folder = Folder.new(folder_params)
    respond_to do |format|
      if @folder.save
        format.html { redirect_to @folder, notice: 'Folder was successfully created.' }
        format.json { render :show, status: :created, location: @folder }
      else
        format.html { render :new }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /folders/1
  # PATCH/PUT /folders/1.json
  def update
    respond_to do |format|
      if @folder.update(folder_params)
        format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
        format.json { render :show, status: :ok, location: @folder }
      else
        format.html { render :edit }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folders/1
  # DELETE /folders/1.json
  def destroy
    @folder.destroy
    respond_to do |format|
      format.html { redirect_to folders_url, notice: 'Folder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_folder
    @folder = Folder.find(params[:id])
  end

  def set_folder_with_name
    @folder = Folder.where(folder_id: params[:folder_id]=='-1' ? nil : params[:folder_id], name: params[:name])
      #Folder.where(folder_id: params[:folder_id], name: params[:name])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def folder_params
    params.require(:folder).permit(:name, :folder_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render :layout => false
  end

  def index_dev
    render :layout => false
  end

  def features
    render :layout => false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_items_helper.rb
module FileItemsHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/the_files_helper.rb
module TheFilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/file_items/_form.html.erb
<%= form_for(@file_item) do |f| %>
  <% if @file_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@file_item.errors.count, "error") %> prohibited this file_item from being saved:</h2>

      <ul>
      <% @file_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </div>
    <div class="field">
        <%= f.label :folder_id %><br>
        <%= f.text_field :folder_id  %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/file_items/edit.html.erb
<h1>Editing File Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @file_item %> |
<%= link_to 'Back', file_items_path %>

app/views/file_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing File Items</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @file_items.each do |file_item| %>
      <tr>
        <td><%= link_to file_item.name, file_item %></td>
        <td><%= link_to 'Edit', edit_file_item_path(file_item) %></td>
        <td><%= link_to 'Destroy', file_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New File item', new_file_item_path %>

app/views/file_items/new.html.erb
<h1>New File Item</h1>

<%= render 'form' %>

<%= link_to 'Back', file_items_path %>

app/views/file_items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_file_item_path(@file_item) %> |
<%= link_to 'Back', file_items_path %>

app/views/folders/_form.html.erb
<%= form_for(@folder) do |f| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% @folder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
        <%= f.label :folder_id %><br>
        <%= f.text_field :folder_id %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/folders/edit.html.erb
<h1>Editing Folder</h1>

<%= render 'form' %>

<%= link_to 'Show', @folder %> |
<%= link_to 'Back', folders_path %>

app/views/folders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Folders</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @folders.each do |folder| %>
      <tr>
        <td><%= link_to folder.name, folder %></td>
        <td><%= link_to 'Edit', edit_folder_path(folder) %></td>
        <td><%= link_to 'Destroy', folder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Folder', new_folder_path %>

app/views/folders/new.html.erb
<h1>New Folder</h1>

<%= render 'form' %>

<%= link_to 'Back', folders_path %>

app/views/folders/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_folder_path(@folder) %> |
<%= link_to 'Back', folders_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/features.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <%= javascript_include_tag 'application_dev', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <style type="text/css">
        .topcorner{
            position:absolute;
            top:0;
            left:0;
        }
        .window {
            position: absolute;
            width: 200px;
            height: 200px;
            background: whitesmoke;
            z-index: 100;
            margin: 0;
            padding: 0;
        }
        .center {
            margin-top: 20%;
        }
    </style>
    <script type="text/javascript">
        angular.module('app', ['templates'])
            .controller('Ctrl', function($scope) {
                $scope.items = [];
                $scope.$on('add_item', function(event, data) {
                    $scope.items.push(data);
                })
            })
            .directive('addItemDialog', function() {
                return {
                    restrict: 'E',
                    templateUrl: 'add-item-dialog.html',
                    link: function(scope, element, attrs) {
                        scope.dialogVisibility = true;
                        scope.item="gfdgf";
                        scope.showDialog = function () {
                            scope.dialogVisibility = false;
                        };
                        scope.add = function() {
                            if (scope.item != "")
                                scope.$emit('add_item', scope.item);
                            scope.item = "";
                            scope.dialogVisibility = true;
                        };
                        scope.close = function() {
                            scope.item = "";
                            scope.dialogVisibility = true;
                        }
                    }
                }
            })
            .directive('anotherAddItemDialog', function() {
                return {
                    restrict: 'E',
                    scope: {
                        'dialog': '=dialog'
                    },
                    link: function(scope, element, attrs) {
                        scope.name = 'bilal';
                        scope.count = 0;
                        scope.click = function() {
                            scope.count += 1;
                            attrs.dialog += scope.name;
                        }
                    },
                    templateUrl: 'test-template.html'
                }
            }).directive('simpleDirective', function() {
                    return {
                        restrict: 'E',
                        scope: {
                            'dialog': '=dialog'
                        },
                        link: function(scope, element, attrs) {
                            scope.name = 'bilal';
                            scope.count = 0;
                            scope.click = function() {
                                scope.count += 1;
                                attrs.dialog += scope.name;
                            }
                        },
                        templateUrl: 'test-template.html'
                    }
                });
    </script>
</head>
<body ng-app="app" ng-controller="Ctrl" style="margin-top: 50px">
    <script type="text/ng-template" id="test-template.html">
        <button ng-click="click()" class="btn btn-default">count</button>
        <div> {{ dialog + ' ' + name + ' ' + count }} </div>
    </script>
    <script type="text/ng-template" id="dialog-template.html">
        <button ng-click="dialog.showDialog()" class="btn btn-primary">
            add
        </button>

        <div ng-hide="dialog.dialogVisibility" class="modal" style="display: block;">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button ng-click="dialog.close()" type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Add item</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-horizontal">
                            <div>
                                <label for="exampleInputName2">item:</label>
                                <input ng-model="dialog.item" type="text" class="form-control" id="exampleInputName2">
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button ng-click="dialog.close()" type="button" class="btn btn-default" data-dismiss="modal" >Cancel</button>
                        <button ng-click="dialog.add()" type="button" class="btn btn-primary">Add</button>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
    </script>
    <div class="container">
        <add-item-dialog></add-item-dialog>
        <div>
            <span ng-show="!items.length">No items</span>
            <ul>
                <li ng-repeat="item in items"> {{ item }} </li>
            </ul>
        </div>
    </div>
</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>App</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">

    </script>

</head>
<body ng-app="mcApp" ng-controller="KeyboardHandlerCtrl" ng-keypress="onKeyPress($event)">
<div ng-controller="TerminalCtrl" >
    <div class="files" ng-controller="FilesCtrl">
        <div class="tab">
            <table>
                <tr ng-repeat="file in leftTab.filesToShow" ng-class="{ 'selected' : $index == leftTab.index.local }">
                    <td>{{ file.name }}</td>
                    <td>{{ file.created_at }}</td>
                </tr>
                <tr ng-repeat="line in (15-leftTab.files.list.length) | range">
                    <td></td>
                    <td></td>
                </tr>
            </table>
        </div>
        <div class="tab">
            <table>
                <tr ng-repeat="file in rightTab.filesToShow" ng-class="{ 'selected' : $index == rightTab.index.local }">
                    <td>{{ file.name }}</td>
                    <td>{{ file.created_at }}</td>
                </tr>
                <tr ng-repeat="line in (15-rightTab.files.list.length) | range">
                    <td></td>
                    <td></td>
                </tr>
            </table>
        </div>

    </div>
    <div class="console">root@root:/ {{ input }}<span class="blink1">&#9646;</span></div>
    <div class="bottom-panel"></div>
</div>

</body>
</html>

app/views/welcome/index_dev.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>App</title>
    <!link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application_dev', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">

    </script>

</head>
<body ng-app="mcApp" ng-controller="KeyboardHandlerCtrl" ng-keypress="onKeyPress($event)">
<div ng-controller="TerminalCtrl" >
    <div ng-controller="FilesCtrl">
        <div class="files">
            <div>
                <ul>
                    <li>first - {{ leftTab.files[0] }}</li>
                    <li>first - {{ leftTab.prev_loc }}</li>
                    <li>current dir - {{ currentDir }}</li>
                </ul>
            </div>
            <div class="tab">
                <table>
                    <tr ng-repeat="file in leftTab.filesToShow" ng-class="{ 'selected' : $index == leftTab.index.local }">
                        <td>{{ file.name }}</td>
                        <td>{{ file.created_at }}</td>
                    </tr>
                    <tr ng-repeat="line in (15-leftTab.files.list.length) | range">
                        <td></td>
                        <td></td>
                    </tr>
                </table>
            </div>
            <div class="tab">
                <table>
                    <tr ng-repeat="file in rightTab.filesToShow" ng-class="{ 'selected' : $index == rightTab.index.local }">
                        <td>{{ file.name }}</td>
                        <td>{{ file.created_at }}</td>
                    </tr>
                    <tr ng-repeat="line in (15-rightTab.files.list.length) | range">
                        <td></td>
                        <td></td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="bottom-panel">
            <add-item-dialog></add-item-dialog>
        </div>
    </div>
    <div class="console">root@root:/ {{ input }}<span class="blink1">&#9646;</span></div>

</div>

</body>
</html>